// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package yamljsonconverter.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the YamlJSONConverter module
	public static void aT_Test(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("YamlJSONConverter.AT_Test").withParams(params).execute(context);
	}
	public static void test_JSONYaml(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("YamlJSONConverter.Test_JSONYaml").withParams(params).execute(context);
	}
	public static void test_YamlJSON(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("YamlJSONConverter.Test_YamlJSON").withParams(params).execute(context);
	}
}