// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package yamljsonconverter.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import yamljsonconverter.helpers.YamlJSONhelper;

/**
 * Returns a JSON string
 */
public class JS_YamlToJSON extends CustomJavaAction<java.lang.String>
{
	private java.lang.String Yaml;

	public JS_YamlToJSON(IContext context, java.lang.String Yaml)
	{
		super(context);
		this.Yaml = Yaml;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return YamlJSONhelper.convertYamlToJson(Yaml);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JS_YamlToJSON";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
